openapi: 3.0.0
info:
  title: Payment Management API
  version: 1.0.0
paths:
  /payments:
    get:
      summary: List all payments
      operationId: listPayments
      responses:
        '200':
          description: A JSON array of payments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Payment'
    post:
      summary: Create a new payment
      operationId: createPayment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPayment'
      responses:
        '201':
          description: Payment created
components:
  schemas:
    Payment:
      type: object
      properties:
        cardNumber:
          type: string
        amount:
          type: number
        paymentDate:
          type: string
          format: date
        description:
          type: string
    NewPayment:
      type: object
      properties:
        cardNumber:
          type: string
        amount:
          type: number
        paymentDate:
          type: string
          format: date
        description:
          type: string
